### ISSUE TITLE
Convert kelvin to Celsius

### ISSUE THREAD

**Issue by medipakpagare** [dipakpagare/weather#1]
Convert kelvin to Celsius for the temperature data in the script.js file. Maybe you can make a function to convert it.

**Comment by vaishnavsonawane** [comment]
<script>
        var cTemp = 100; // temperature in Celsius
 
        var hTemp = ((cTemp * 9) /5 ) + 32;
        document.write("Temperature in Celsius: " + cTemp + " degrees<br/>");
        document.write("Temperature in Fahrenheit: " + hTemp + " degrees");
    </script>

**Comment by vaishnavsonawane** [comment]
<script>
        var cTemp = 100; // temperature in Celsius
        // Let's be generous with parentheses
        var hTemp = ((cTemp * 9) /5 ) + 32;
        document.write("Temperature in Celsius: " + cTemp + " degrees<br/>");
        document.write("Temperature in Fahrenheit: " + hTemp + " degrees");
    </script>

**Comment by vaishnavsonawane** [comment]
`<script>
        var cTemp = 100; // temperature in Celsius
        // Let's be generous with parentheses
        var hTemp = ((cTemp * 9) /5 ) + 32;
        document.write("Temperature in Celsius: " + cTemp + " degrees<br/>");
        document.write("Temperature in Fahrenheit: " + hTemp + " degrees");
    </script>`

**Comment by vaishnavsonawane** [comment]
`<script>
        var cTemp = 100; // temperature in Celsius
        var hTemp = ((cTemp * 9) /5 ) + 32;
        document.write("Temperature in Celsius: " + cTemp + " degrees<br/>");
        document.write("Temperature in Fahrenheit: " + hTemp + " degrees");
    </script>`

**Comment by medipakpagare** [comment]
> `<script> var cTemp = 100; // temperature in Celsius var hTemp = ((cTemp * 9) /5 ) + 32; document.write("Temperature in Celsius: " + cTemp + " degrees<br/>"); document.write("Temperature in Fahrenheit: " + hTemp + " degrees"); </script>

Fork the repo and do a pull request. Try to do changes in the project itself.

**Comment by Koda-Pig** [comment]
Hiya @dipakpagare can I work on this?

**Comment by medipakpagare** [comment]
> Hiya @dipakpagare can I work on this?

Yes, sure.

**Comment by Koda-Pig** [comment]
My pull request here: https://github.com/dipakpagare/weather/pull/4
